version: '2'

services:
  # dependency services
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=ratings:1:1

  # our services
  importer:
    image: timonback/newsforyou-importer:1.0
    environment:
      - MONGO_ADDRESS=mongo_1
    depends_on:
      - mongo
    links:
      - mongo

  recommendator:
    image: timonback/newsforyou-recommendator:1.0
    environment:
      - MONGO_ADDRESS=mongo_1
    depends_on:
      - mongo
    links:
      - mongo

  visualization:
    image: timonback/newsforyou-visualization:1.0
    ports:
      - "9000:9000"
    environment:
      - MONGO_ADDRESS=mongo_1
    depends_on:
      - mongo
    links:
      - mongo

