version: '2'

services:
  importer:
    image: timonback/newsforyou-visualization:1.0
    depends_on:
      - mongo
    links:
      - "mongo:mongoPrimaryNode"

  recommendator:
    image: timonback/newsforyou-recommendator:1.0
    depends_on:
      - mongo
    links:
      - "mongo:mongoPrimaryNode"


  visualization:
    image: timonback/newsforyou-visualization:1.0
    ports:
      - "9000:9000"
    environment:
      - MONGO_ADDRESS=mongoPrimaryNode
    depends_on:
      - mongo
    links:
      - "mongo:mongoPrimaryNode"

  mongo:
    image: mongo
    ports:
      - "27017:27017"

